# Generated by Django 5.1.4 on 2024-12-08 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgesVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('upload_date', models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 8, 16, 31, 41, 33120))),
                ('upload_file', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
