# Generated by Django 5.1.4 on 2024-12-08 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agesverification',
            name='upload_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 8, 19, 10, 27, 133102)),
        ),
    ]
